// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SantaUrsula.API.Data;

#nullable disable

namespace SantaUrsula.API.Migrations
{
    [DbContext(typeof(SantaUrsulaDbContext))]
    partial class SantaUrsulaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<int>("PermisoId")
                        .HasColumnType("integer");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("RolPermisos", (string)null);
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Auditorium", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DireccionIP")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RegistroAfectadoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("text");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK__Auditori__3214EC079A4B9780");

                    b.HasIndex(new[] { "TablaAfectada", "RegistroAfectadoId" }, "IX_Auditoria_Tabla_Registro");

                    b.HasIndex(new[] { "UsuarioId", "FechaHora" }, "IX_Auditoria_Usuario_Fecha");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.CarasDentale", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<byte>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id")
                        .HasName("PK__CarasDen__3214EC07607CAE4E");

                    b.HasIndex(new[] { "Nombre" }, "UQ_Caras_Nombre")
                        .IsUnique();

                    b.ToTable("CarasDentales");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreadoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<byte>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("HistoriaClinicaId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__Citas__3214EC075D2DB155");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("HistoriaClinicaId");

                    b.HasIndex(new[] { "Fecha", "Hora" }, "IX_Citas_Fecha");

                    b.HasIndex(new[] { "PacienteId", "Fecha" }, "IX_Citas_PacienteId");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.ConfiguracionSistema", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Clave")
                        .HasName("PK__Configur__E8181E10CA72FCD3");

                    b.ToTable("ConfiguracionSistema", (string)null);
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Diagnostico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("CodigoCIE10")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id")
                        .HasName("PK__Diagnost__3214EC07CB16B9FE");

                    b.HasIndex(new[] { "Nombre" }, "IX_Diagnosticos_Nombre");

                    b.HasIndex(new[] { "CodigoCIE10" }, "UQ_Diagnosticos_CIE10")
                        .IsUnique();

                    b.ToTable("Diagnosticos");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("GeneradoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("HistoriaClinicaId")
                        .HasColumnType("integer");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("HistoriaClinicaPDF");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id")
                        .HasName("PK__Document__3214EC077C29138B");

                    b.HasIndex("GeneradoPorUsuarioId");

                    b.HasIndex(new[] { "HistoriaClinicaId" }, "IX_Documentos_HistoriaClinicaId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.EstadosCitum", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<byte>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id")
                        .HasName("PK__EstadosC__3214EC07D5AD3083");

                    b.HasIndex(new[] { "Nombre" }, "UQ_EstadosCita_Nombre")
                        .IsUnique();

                    b.ToTable("EstadosCita");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.EstadosHistorium", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<byte>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id")
                        .HasName("PK__EstadosH__3214EC07D567E55F");

                    b.HasIndex(new[] { "Nombre" }, "UQ_EstadosHistoria_Nombre")
                        .IsUnique();

                    b.ToTable("EstadosHistoria");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.EstadosPiezaOdontograma", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<byte>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id")
                        .HasName("PK__EstadosP__3214EC07D9ABFC74");

                    b.HasIndex(new[] { "Nombre" }, "UQ_EstadosPieza_Nombre")
                        .IsUnique();

                    b.ToTable("EstadosPiezaOdontograma", (string)null);
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.EvaluacionesPeriodontale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BolsaPeriodontal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("CalculosInfragingivales")
                        .HasColumnType("boolean");

                    b.Property<string>("Especificaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool?>("Gingivitis")
                        .HasColumnType("boolean");

                    b.Property<int>("HistoriaClinicaId")
                        .HasColumnType("integer");

                    b.Property<bool?>("PbBlanda")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PbDura")
                        .HasColumnType("boolean");

                    b.Property<string>("Pronostico")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id")
                        .HasName("PK__Evaluaci__3214EC075DCF469C");

                    b.HasIndex(new[] { "HistoriaClinicaId" }, "UQ_EvalPeriodontal_Historia")
                        .IsUnique();

                    b.ToTable("EvaluacionesPeriodontales");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.HistoriaDiagnostico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiagnosticoId")
                        .HasColumnType("integer");

                    b.Property<int>("HistoriaClinicaId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id")
                        .HasName("PK__Historia__3214EC078BA3A1B9");

                    b.HasIndex(new[] { "DiagnosticoId" }, "IX_HistoriaDiagnosticos_DiagnosticoId");

                    b.HasIndex(new[] { "HistoriaClinicaId", "DiagnosticoId", "Tipo" }, "UQ_HistoriaDiag")
                        .IsUnique();

                    b.ToTable("HistoriaDiagnosticos");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.HistoriasClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AntecedentesFamiliares")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AntecedentesPatologicos")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("AnuladoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("AtencionCorrigeId")
                        .HasColumnType("integer");

                    b.Property<bool?>("Dolor")
                        .HasColumnType("boolean");

                    b.Property<byte>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1);

                    b.Property<bool?>("ExtraccionesPrevias")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("FechaHoraAtencion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gestante")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool?>("HemorragiaExcesiva")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicacionActual")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("MotivoConsulta")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NumeroHistoria")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<bool?>("ProblemasPostExtraccion")
                        .HasColumnType("boolean");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("integer");

                    b.Property<string>("TiempoEnfermedad")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("UltimaVisitaOdontologo")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__Historia__3214EC07C2A21A98");

                    b.HasIndex("AnuladoPorUsuarioId");

                    b.HasIndex("AtencionCorrigeId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("ProfesionalId");

                    b.HasIndex(new[] { "PacienteId", "FechaHoraAtencion" }, "IX_Historias_PacienteId")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "NumeroHistoria" }, "UQ_Historias_NumeroHistoria")
                        .IsUnique()
                        .HasFilter("(\"NumeroHistoria\" IS NOT NULL)");

                    b.ToTable("HistoriasClinicas", t =>
                        {
                            t.HasTrigger("trg_HistoriasClinicas_Auditoria");

                            t.HasTrigger("trg_HistoriasClinicas_ProtegerEstado");
                        });
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.MovimientosCuentum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Debe")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Haber")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("HistoriaClinicaId")
                        .HasColumnType("integer");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<int>("RegistradoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<byte>("TipoMovimientoId")
                        .HasColumnType("smallint");

                    b.Property<int?>("TratamientoId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__Movimien__3214EC07A7F0B971");

                    b.HasIndex("HistoriaClinicaId");

                    b.HasIndex("RegistradoPorUsuarioId");

                    b.HasIndex("TipoMovimientoId");

                    b.HasIndex("TratamientoId");

                    b.HasIndex(new[] { "PacienteId", "Fecha", "Id" }, "IX_MovimientosCuenta_Paciente_Fecha");

                    b.ToTable("MovimientosCuenta", t =>
                        {
                            t.HasTrigger("trg_MovimientosCuenta_Auditoria");

                            t.HasTrigger("trg_MovimientosCuenta_ValidarNaturaleza");
                        });
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.OdontogramaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte?>("CaraDentalId")
                        .HasColumnType("smallint");

                    b.Property<byte>("EstadoId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("HistoriaClinicaId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<short>("PiezaDentalId")
                        .HasColumnType("smallint");

                    b.HasKey("Id")
                        .HasName("PK__Odontogr__3214EC07FE25FD69");

                    b.HasIndex("CaraDentalId");

                    b.HasIndex("EstadoId");

                    b.HasIndex(new[] { "HistoriaClinicaId" }, "IX_Odontograma_HistoriaClinicaId");

                    b.HasIndex(new[] { "PiezaDentalId", "FechaRegistro" }, "IX_Odontograma_Pieza")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "HistoriaClinicaId", "PiezaDentalId", "CaraDentalId" }, "UQ_Odontograma_Historia_Pieza_Cara")
                        .IsUnique()
                        .HasFilter("(\"CaraDentalId\" IS NOT NULL)");

                    b.HasIndex(new[] { "HistoriaClinicaId", "PiezaDentalId" }, "UQ_Odontograma_Historia_Pieza_SinCara")
                        .IsUnique()
                        .HasFilter("(\"CaraDentalId\" IS NULL)");

                    b.ToTable("OdontogramaDetalle", (string)null);
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Alergias")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CelularAcompanante")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("DomicilioActual")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LugarNacimiento")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("LugarProcedencia")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreAcompanante")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ocupacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Religion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte>("SexoId")
                        .HasColumnType("smallint");

                    b.HasKey("Id")
                        .HasName("PK__Paciente__3214EC07D540C251");

                    b.HasIndex("SexoId");

                    b.HasIndex(new[] { "ApellidoPaterno", "ApellidoMaterno", "Nombres" }, "IX_Pacientes_Apellidos");

                    b.HasIndex(new[] { "DNI" }, "UQ_Pacientes_DNI")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("PK__Permisos__3214EC073E8676F1");

                    b.HasIndex(new[] { "Modulo", "Accion" }, "UQ_Permisos_Modulo_Accion")
                        .IsUnique();

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.PiezasDentale", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<short>("Codigo")
                        .HasColumnType("smallint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id")
                        .HasName("PK__PiezasDe__3214EC071EBD3F5A");

                    b.HasIndex(new[] { "Codigo" }, "UQ_Piezas_Codigo")
                        .IsUnique();

                    b.ToTable("PiezasDentales");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC07E4215054");

                    b.HasIndex(new[] { "Nombre" }, "UQ_Roles_Nombre")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Sexo", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<byte>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id")
                        .HasName("PK__Sexos__3214EC070097A34C");

                    b.HasIndex(new[] { "Nombre" }, "UQ_Sexos_Nombre")
                        .IsUnique();

                    b.ToTable("Sexos");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.TiposMovimientoCuentum", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<byte>("Id"));

                    b.Property<string>("Naturaleza")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("character(1)")
                        .IsFixedLength();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id")
                        .HasName("PK__TiposMov__3214EC0709934156");

                    b.HasIndex(new[] { "Nombre" }, "UQ_TiposMovimiento_Nombre")
                        .IsUnique();

                    b.ToTable("TiposMovimientoCuenta");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.TiposTratamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("PrecioReferencial")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool>("RequiereCara")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequierePieza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id")
                        .HasName("PK__TiposTra__3214EC074E63E24E");

                    b.HasIndex(new[] { "Nombre" }, "UQ_TiposTratamiento_Nombre")
                        .IsUnique();

                    b.ToTable("TiposTratamiento", (string)null);
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Tratamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Planificado");

                    b.Property<DateOnly>("FechaAplicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<int>("HistoriaClinicaId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<short?>("PiezaDentalId")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("TipoTratamientoId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__Tratamie__3214EC07761047BC");

                    b.HasIndex("PiezaDentalId");

                    b.HasIndex(new[] { "HistoriaClinicaId" }, "IX_Tratamientos_HistoriaClinicaId");

                    b.HasIndex(new[] { "TipoTratamientoId" }, "IX_Tratamientos_TipoTratamientoId");

                    b.ToTable("Tratamientos");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PK__Usuarios__3214EC079714764D");

                    b.HasIndex("RolId");

                    b.HasIndex(new[] { "Email" }, "UQ_Usuarios_Email")
                        .IsUnique()
                        .HasFilter("(\"Email\" IS NOT NULL)");

                    b.HasIndex(new[] { "NombreUsuario" }, "UQ_Usuarios_NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.vw_OdontogramaVigentePorPaciente", b =>
                {
                    b.Property<byte?>("CaraDentalId")
                        .HasColumnType("smallint");

                    b.Property<byte>("EstadoId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HistoriaClinicaId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<short>("PiezaDentalId")
                        .HasColumnType("smallint");

                    b.ToTable((string)null);

                    b.ToView("vw_OdontogramaVigentePorPaciente", (string)null);
                });

            modelBuilder.Entity("TratamientoCara", b =>
                {
                    b.Property<int>("TratamientoId")
                        .HasColumnType("integer");

                    b.Property<byte>("CaraDentalId")
                        .HasColumnType("smallint");

                    b.HasKey("TratamientoId", "CaraDentalId");

                    b.HasIndex("CaraDentalId");

                    b.ToTable("TratamientoCaras", (string)null);
                });

            modelBuilder.Entity("RolPermiso", b =>
                {
                    b.HasOne("SantaUrsula.API.Data.Models.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .IsRequired()
                        .HasConstraintName("FK_RolPermisos_Permisos");

                    b.HasOne("SantaUrsula.API.Data.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_RolPermisos_Roles");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Auditorium", b =>
                {
                    b.HasOne("SantaUrsula.API.Data.Models.Usuario", "Usuario")
                        .WithMany("Auditoria")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK_Auditoria_Usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Cita", b =>
                {
                    b.HasOne("SantaUrsula.API.Data.Models.Usuario", "CreadoPorUsuario")
                        .WithMany("Cita")
                        .HasForeignKey("CreadoPorUsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Citas_CreadoPor");

                    b.HasOne("SantaUrsula.API.Data.Models.EstadosCitum", "Estado")
                        .WithMany("Cita")
                        .HasForeignKey("EstadoId")
                        .IsRequired()
                        .HasConstraintName("FK_Citas_Estado");

                    b.HasOne("SantaUrsula.API.Data.Models.HistoriasClinica", "HistoriaClinica")
                        .WithMany("Cita")
                        .HasForeignKey("HistoriaClinicaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Citas_Historia");

                    b.HasOne("SantaUrsula.API.Data.Models.Paciente", "Paciente")
                        .WithMany("Cita")
                        .HasForeignKey("PacienteId")
                        .IsRequired()
                        .HasConstraintName("FK_Citas_Paciente");

                    b.Navigation("CreadoPorUsuario");

                    b.Navigation("Estado");

                    b.Navigation("HistoriaClinica");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Documento", b =>
                {
                    b.HasOne("SantaUrsula.API.Data.Models.Usuario", "GeneradoPorUsuario")
                        .WithMany("Documentos")
                        .HasForeignKey("GeneradoPorUsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Documentos_Usuario");

                    b.HasOne("SantaUrsula.API.Data.Models.HistoriasClinica", "HistoriaClinica")
                        .WithMany("Documentos")
                        .HasForeignKey("HistoriaClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Documentos_Historia");

                    b.Navigation("GeneradoPorUsuario");

                    b.Navigation("HistoriaClinica");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.EvaluacionesPeriodontale", b =>
                {
                    b.HasOne("SantaUrsula.API.Data.Models.HistoriasClinica", "HistoriaClinica")
                        .WithOne("EvaluacionesPeriodontale")
                        .HasForeignKey("SantaUrsula.API.Data.Models.EvaluacionesPeriodontale", "HistoriaClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EvalPeriodontal_Historia");

                    b.Navigation("HistoriaClinica");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.HistoriaDiagnostico", b =>
                {
                    b.HasOne("SantaUrsula.API.Data.Models.Diagnostico", "Diagnostico")
                        .WithMany("HistoriaDiagnosticos")
                        .HasForeignKey("DiagnosticoId")
                        .IsRequired()
                        .HasConstraintName("FK_HistoriaDiag_Diagnostico");

                    b.HasOne("SantaUrsula.API.Data.Models.HistoriasClinica", "HistoriaClinica")
                        .WithMany("HistoriaDiagnosticos")
                        .HasForeignKey("HistoriaClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HistoriaDiag_Historia");

                    b.Navigation("Diagnostico");

                    b.Navigation("HistoriaClinica");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.HistoriasClinica", b =>
                {
                    b.HasOne("SantaUrsula.API.Data.Models.Usuario", "AnuladoPorUsuario")
                        .WithMany("HistoriasClinicaAnuladoPorUsuarios")
                        .HasForeignKey("AnuladoPorUsuarioId")
                        .HasConstraintName("FK_Historias_AnuladoPor");

                    b.HasOne("SantaUrsula.API.Data.Models.HistoriasClinica", "AtencionCorrige")
                        .WithMany("InverseAtencionCorrige")
                        .HasForeignKey("AtencionCorrigeId")
                        .HasConstraintName("FK_Historias_Corrige");

                    b.HasOne("SantaUrsula.API.Data.Models.EstadosHistorium", "Estado")
                        .WithMany("HistoriasClinicas")
                        .HasForeignKey("EstadoId")
                        .IsRequired()
                        .HasConstraintName("FK_Historias_Estado");

                    b.HasOne("SantaUrsula.API.Data.Models.Paciente", "Paciente")
                        .WithMany("HistoriasClinicas")
                        .HasForeignKey("PacienteId")
                        .IsRequired()
                        .HasConstraintName("FK_Historias_Pacientes");

                    b.HasOne("SantaUrsula.API.Data.Models.Usuario", "Profesional")
                        .WithMany("HistoriasClinicaProfesionals")
                        .HasForeignKey("ProfesionalId")
                        .IsRequired()
                        .HasConstraintName("FK_Historias_Profesional");

                    b.Navigation("AnuladoPorUsuario");

                    b.Navigation("AtencionCorrige");

                    b.Navigation("Estado");

                    b.Navigation("Paciente");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.MovimientosCuentum", b =>
                {
                    b.HasOne("SantaUrsula.API.Data.Models.HistoriasClinica", "HistoriaClinica")
                        .WithMany("MovimientosCuenta")
                        .HasForeignKey("HistoriaClinicaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Movimientos_Historia");

                    b.HasOne("SantaUrsula.API.Data.Models.Paciente", "Paciente")
                        .WithMany("MovimientosCuenta")
                        .HasForeignKey("PacienteId")
                        .IsRequired()
                        .HasConstraintName("FK_Movimientos_Paciente");

                    b.HasOne("SantaUrsula.API.Data.Models.Usuario", "RegistradoPorUsuario")
                        .WithMany("MovimientosCuenta")
                        .HasForeignKey("RegistradoPorUsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Movimientos_Usuario");

                    b.HasOne("SantaUrsula.API.Data.Models.TiposMovimientoCuentum", "TipoMovimiento")
                        .WithMany("MovimientosCuenta")
                        .HasForeignKey("TipoMovimientoId")
                        .IsRequired()
                        .HasConstraintName("FK_Movimientos_Tipo");

                    b.HasOne("SantaUrsula.API.Data.Models.Tratamiento", "Tratamiento")
                        .WithMany("MovimientosCuenta")
                        .HasForeignKey("TratamientoId")
                        .HasConstraintName("FK_Movimientos_Tratamiento");

                    b.Navigation("HistoriaClinica");

                    b.Navigation("Paciente");

                    b.Navigation("RegistradoPorUsuario");

                    b.Navigation("TipoMovimiento");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.OdontogramaDetalle", b =>
                {
                    b.HasOne("SantaUrsula.API.Data.Models.CarasDentale", "CaraDental")
                        .WithMany("OdontogramaDetalles")
                        .HasForeignKey("CaraDentalId")
                        .HasConstraintName("FK_Odontograma_Cara");

                    b.HasOne("SantaUrsula.API.Data.Models.EstadosPiezaOdontograma", "Estado")
                        .WithMany("OdontogramaDetalles")
                        .HasForeignKey("EstadoId")
                        .IsRequired()
                        .HasConstraintName("FK_Odontograma_Estado");

                    b.HasOne("SantaUrsula.API.Data.Models.HistoriasClinica", "HistoriaClinica")
                        .WithMany("OdontogramaDetalles")
                        .HasForeignKey("HistoriaClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Odontograma_Historia");

                    b.HasOne("SantaUrsula.API.Data.Models.PiezasDentale", "PiezaDental")
                        .WithMany("OdontogramaDetalles")
                        .HasForeignKey("PiezaDentalId")
                        .IsRequired()
                        .HasConstraintName("FK_Odontograma_Pieza");

                    b.Navigation("CaraDental");

                    b.Navigation("Estado");

                    b.Navigation("HistoriaClinica");

                    b.Navigation("PiezaDental");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Paciente", b =>
                {
                    b.HasOne("SantaUrsula.API.Data.Models.Sexo", "Sexo")
                        .WithMany("Pacientes")
                        .HasForeignKey("SexoId")
                        .IsRequired()
                        .HasConstraintName("FK_Pacientes_Sexo");

                    b.Navigation("Sexo");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Tratamiento", b =>
                {
                    b.HasOne("SantaUrsula.API.Data.Models.HistoriasClinica", "HistoriaClinica")
                        .WithMany("Tratamientos")
                        .HasForeignKey("HistoriaClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Tratamientos_Historia");

                    b.HasOne("SantaUrsula.API.Data.Models.PiezasDentale", "PiezaDental")
                        .WithMany("Tratamientos")
                        .HasForeignKey("PiezaDentalId")
                        .HasConstraintName("FK_Tratamientos_Pieza");

                    b.HasOne("SantaUrsula.API.Data.Models.TiposTratamiento", "TipoTratamiento")
                        .WithMany("Tratamientos")
                        .HasForeignKey("TipoTratamientoId")
                        .IsRequired()
                        .HasConstraintName("FK_Tratamientos_Tipo");

                    b.Navigation("HistoriaClinica");

                    b.Navigation("PiezaDental");

                    b.Navigation("TipoTratamiento");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Usuario", b =>
                {
                    b.HasOne("SantaUrsula.API.Data.Models.Role", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Roles");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("TratamientoCara", b =>
                {
                    b.HasOne("SantaUrsula.API.Data.Models.CarasDentale", null)
                        .WithMany()
                        .HasForeignKey("CaraDentalId")
                        .IsRequired()
                        .HasConstraintName("FK_TratamientoCaras_Cara");

                    b.HasOne("SantaUrsula.API.Data.Models.Tratamiento", null)
                        .WithMany()
                        .HasForeignKey("TratamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TratamientoCaras_Tratamiento");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.CarasDentale", b =>
                {
                    b.Navigation("OdontogramaDetalles");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Diagnostico", b =>
                {
                    b.Navigation("HistoriaDiagnosticos");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.EstadosCitum", b =>
                {
                    b.Navigation("Cita");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.EstadosHistorium", b =>
                {
                    b.Navigation("HistoriasClinicas");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.EstadosPiezaOdontograma", b =>
                {
                    b.Navigation("OdontogramaDetalles");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.HistoriasClinica", b =>
                {
                    b.Navigation("Cita");

                    b.Navigation("Documentos");

                    b.Navigation("EvaluacionesPeriodontale");

                    b.Navigation("HistoriaDiagnosticos");

                    b.Navigation("InverseAtencionCorrige");

                    b.Navigation("MovimientosCuenta");

                    b.Navigation("OdontogramaDetalles");

                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Paciente", b =>
                {
                    b.Navigation("Cita");

                    b.Navigation("HistoriasClinicas");

                    b.Navigation("MovimientosCuenta");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.PiezasDentale", b =>
                {
                    b.Navigation("OdontogramaDetalles");

                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Sexo", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.TiposMovimientoCuentum", b =>
                {
                    b.Navigation("MovimientosCuenta");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.TiposTratamiento", b =>
                {
                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Tratamiento", b =>
                {
                    b.Navigation("MovimientosCuenta");
                });

            modelBuilder.Entity("SantaUrsula.API.Data.Models.Usuario", b =>
                {
                    b.Navigation("Auditoria");

                    b.Navigation("Cita");

                    b.Navigation("Documentos");

                    b.Navigation("HistoriasClinicaAnuladoPorUsuarios");

                    b.Navigation("HistoriasClinicaProfesionals");

                    b.Navigation("MovimientosCuenta");
                });
#pragma warning restore 612, 618
        }
    }
}
